data_dict = {"B-COMPANY": [],
 "B-COMPANY-DURATION": ["June 2013", "Present", "March 2010", "May 2013", "quality"],
 "B-COMPANY-LOCATION": [],
 "B-CURR-COMPANY": "Chennai, Tamil",
 "B-CURR-DESIGNATION": "Dev-Test",
 "B-CURR-LOCATION": "Nadu,",
 "B-DESIGNATION": ["Cognizant"],
 "B-EMAIL": "ganesh.alala@gmail.com",
 "B-GITHUB": ["https://www.linkedin.com/in/ganesh-alala/"],
 "B-INSTAGRAM": ["https://www.instagram.com/ganesh.alala/"],
 "B-LINKEDIN": [],
 "B-PERSON": "Ganesh AlalaSundaram",
 "B-SKILLS": ["Scrum", "Master/Program", "Manager", "problems,", "responsible", "for", "product", "delivery", "and", "building"],
 "B-TWITTER": ["https://twitter.com/ganeshalala"],
 "B-ACHIVE": [],
 "B-AOI": [],
 "B-CAR-OBJ": [[
         "My long-term career objective is to lead programs that solves complex problems, responsible for product",
         "delivery and building products that positively impacts millions of consumers and enterprise users.",
         "Willing to relocate: Anywhere"
         ]
],
"B-CERTIFICATE": [],
"B-COLLEGE": [["Software Product Management"],
              ["Bachelor of Computer Science in Computer Science Engineering"],
              [" Certified ScrumMaster (CSM)"]
              ],
"B-DEGREE": [["Product School -  New York, NY"],
             ["Anna University"],
             ["AWARDS"]
             ],
"B-EDUCATION":
    [["EDUCATION"]],
"B-EXP":
        [],
"B-GRADUATION-END-YEAR": [],
"B-H-SCHOOL": [],
"B-H-SCHOOL-GRADUATION-END-YEAR": [],
"B-HSS-SCHOOL": [],
"B-HSS-SCHOOL-GRADUATION-END-YEAR": [],
"B-OTHER-SKILL": [],
"B-PROJECT-EXP":
    [
     [" Product Technologies: Cloud &amp; Mobile Migrations, DevOps for Test Strategies, Visual Studio,", "Azure.",
      " Orchestrated projects as an Individual Contributor and Led teams across global engagements.",
      " Contributed to 60% of the software component automation in the projects. Streamlined process and",
      "tools for Dev-Ops implementation that included training, metrics and reporting.",
      " Led Manual and Automated Test Management to elevate the quality of Mobile (x Platform), Cloud",
      "and IoT Applications. Designed, Developed and Maintained automation coverage for UI and API",
      "layer by handshaking Visual Studio with Open Source frameworks.",
      " Migrated millions of customers to Azure Cloud through FastTrack program. Developed Tools that",
      "reduced manual efforts worth 40 hours for each process."
      ],
      [" Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
       " Aenean ac interdum nisi. Sed in consequat mi.", "Company Name, Location - Job Title",
       "MONTH 20XX - MONTH 20XX",
       " Built WCF services for iOS and Android Applications for a PoC which helped business to grab more",
       "mobile projects.",
       " Delivered quality of products to customers with the stipulated time. Stand-ups, defect triage,brown",
       "bag sessions, bug-bash and retrospectives. Owned and managed weekly quality report.",
       " Initiated transformation of web to mobile apps within project and assisted senior stakeholders of the",
       "company in analyzing the opportunity.", "PROJECTS", "IoT and Smart City Projects",
       " Formulated the use of VSO Dashboards for ease of status reporting which reduced manual effort of",
       "an hour per day.", " Leveraged developer background to automate UI and API components through C#, Xamarin UI in",
       "iOS and Android apps.", " Led process improvements that standardized operations that included on-boarding/reporting and",
       "customer acceptance.", "PubSec Projects - Dubai/Columbia/New York",
       " Coordinated between in-house and client teams and kept stakeholders informed of progress and",
       "milestones.", " Supervised an avg. of 10-member software QA team in developing and implementing",
       "quality-assurance and quality-control methodologies to ensure compliance with QA standards.",
       " Created tools that helped the development ecosystem by automating the long running manual", "process.",
       " Brought a strong focus on \"voice of the customer\" into the software development function to ensure",
       "product and customer success."]]
     }
# data_dict ={"B-COMPANY": ["India, Operations", "Global", "India"],
#  "B-COMPANY-DURATION": ["August 2012", "January 2016", "all", "February 2011", "July 2012", "September 2009", "January 2011"],
#  "B-COMPANY-LOCATION": [],
#  "B-CURR-COMPANY": "https://twitter.com/aartipimplay",
#  "B-CURR-DESIGNATION": "Pimplay Center",
#  "B-CURR-LOCATION": [],
#  "B-DESIGNATION": ["Microsoft",
#                    "Microsoft",
#                    "Communication",
#                    "Supervisor",
#                    "Managing",
#                    "SITEL Service Desk Analyst technical support end"
#                    ],
#  "B-EMAIL": [],
#  "B-GITHUB": [],
#  "B-INSTAGRAM": "same.",
#  "B-LINKEDIN": "aarti.pimplay@gmail.com",
#  "B-PERSON": [],
#  "B-SKILLS": ["task organization, distribution", "site status enquiries.", "Incidents holders. workflow",
#               "Incident and major incident processes are followed. Escalate events that have a",
#               "MS impacts",
#               "Security or as directed by",
#               "Escalation Matrix.",
#               "problem tickets based on the recurring incidents identified. the problem records to ensure timely closure of issues. Responsible for", "SLA reports.", "OJT, concurrent"],
#  "B-TWITTER": [],
#  "B-ACHIVE": [
#          [" Ability to build teams and motivate them towards team goals."],
#          [" Effective Communication skills."],
#          [" Able to handle and overcome objections."],
#          [" Ability to work effectively in a team environment."],
#          [" Ability to adapt to the changes in organization along with successful implementation of the"],
#          ["change in the system."]
#          ],
#  "B-AOI": [],
#  "B-CAR-OBJ": [["August 2012 to January 2016", "Microsoft India,"]],
#  "B-CERTIFICATE": [],
#  "B-COLLEGE": [],
#  "B-DEGREE":
#      [["Service Desk Analyst"]],
#  "B-EDUCATION": [["SITEL"]],
#  "B-EXP": [
#          ["Operations Center Shift Manager (OCSM)"],
#          [" Handling escalations, notifications, task organization, distribution of work, site status"],
#          ["enquiries."],
#          [" Monitoring the Incidents handled by the team in real time."],
#          [" Supervising the reporting of Incidents to respective stake holders."],
#          [" Ensuring proper workflow of Incident and major incident processes are followed."],
#          [" Escalate events that have a potential MS impacts to Security Analyst or as directed by the"],
#          ["Escalation Matrix."],
#          [" Initiate problem tickets based on the recurring incidents identified."],
#          [" Reviewing the problem records to ensure timely closure of issues."],
#          [" Responsible for publishing monthly SLA reports."],
#          [" Providing OJT, concurrent training."],
#          [" Global news monitoring (Monitor Global activities on a continual basis)."],
#          [" Responsible for administrative duties like reviewing performance Metrics, managing"],
#          ["breaks/lunch (All stations), Shift Changeover Process and adherence, Policy Reviews and"],
#          ["Updates, Supply and equipment requests, OCSM Pass-down Log, Inventory Control,"],
#          ["Employee Recognition Requests, Disciplinary Actions, Annual Evaluations, Mentoring and"],
#          ["Counselling."],
#          [" Maintain and share updates on emergency procedures."],
#          [" Develop and/or update all policies and procedures."],
#          ["Microsoft India"],
#          ["Communication Supervisor"],
#          [" Managing all incidents based on the priorities."],
#          [" Publishing executive business notifications during outages."],
#          [" Responsible for all email communications in GSOC Asia."],
#          [" Global news monitoring."],
#          [" Handling and initiating Major Incident conference calls and assisting the respective teams."],
#          [" Initiating bridge calls for P1 &amp; P2 Issues."],
#          [" Providing overall analysis of incidents by performing root cause analysis and quality checks"],
#          [" Maintain an in-depth knowledge of emergency procedures, and adhere to same."]
#          ],
#  "B-GRADUATION-END-YEAR": [],
#  "B-H-SCHOOL": [],
#  "B-H-SCHOOL-GRADUATION-END-YEAR": [],
#  "B-HSS-SCHOOL": [],
#  "B-HSS-SCHOOL-GRADUATION-END-YEAR": [],
#  "B-OTHER-SKILL": [],
#  "B-PROJECT-EXP": [
#          [" Provide supervision to assigned staff."],
#          [" Provided technical support to end users."],
#          [" Worked as part of escalation team to identify resolution and provide inputs to"],
#          ["improve/create KB articles."],
#          [" Responsible for providing First Call Resolution."],
#          [" Providing Technical assistance to customers based on the priorities."],
#          [" Resolving Issues related to networking."],
#          [" Assist in configuring LAN, Modular Routers and TCP/IP."],
#          [" Troubleshooting Hardware and System performance issues."],
#          [" Working with Users to identify and rectify the issues pertaining to Internet and related"],
#          ["services."],
#          [" Worked with different Antivirus Softwares - Installation and troubleshooting."],
#          [" Team SPOC for Quality and Compliance improvements."]
#          ]}
